### ISSUE TITLE
is it still working?

### ISSUE THREAD

**Issue by boynet** [fradinni/nodejs-statsd-mysql-backend#13]
I am new to the statsd world, anything changes in this 2 years since last commit in the statsd library that will break this from work?

**Comment by dpacaud** [comment]
Hi,

That is a very good question.
I haven't been using statsd recently so I really have no Idea.

**Comment by pespin** [comment]
I confirm I have it working  right now with statsd master v0.9.0 9cf77d87855bcb69a8663135f59aa23825db9797.

**Comment by fradinni** [comment]
Yeah it seems it's still working.
I'm closing the issue.
