### ISSUE TITLE
zero value not stored in database

### ISSUE THREAD

**Issue by pespin** [fradinni/nodejs-statsd-mysql-backend#14]
Hi, looking at current master (4d1febbbd3dc1c965b8772351d3295e73a051eca) I observed zero values are never stored in the database (using grafana).

I now see that the engine clearly avoids storing zero values. The question is: why? I don't see any reason for not storing zero values, specially since code afterwards checks if last value is already the same to avoid storing repeated value.

I so far changed my local set up with this patch to enable zero value storing:
```
diff --git a/engines/gaugesEngine.js b/engines/gaugesEngine.js
index 547108b..9beeafe 100644
--- a/engines/gaugesEngine.js
+++ b/engines/gaugesEngine.js
@@ -17,9 +17,6 @@ MySQLBackendGaugesEngine.prototype.buildQuerries = function(gauges, time_stamp)
         // Iterate on each gauge
     for(var gaugeName in gauges) {
       var gaugeValue = gauges[gaugeName];
-      if(gaugeValue === 0) {
-        continue;
-      } else {
           /**********************************************************************
            * Edit following line to customize where statsd datas are inserted
            *
@@ -32,9 +29,8 @@ MySQLBackendGaugesEngine.prototype.buildQuerries = function(gauges, time_stamp)
           // If it is different, we insert a new line.
           // If gaugeName does not exist in the table, we insert a new line
           // The -678 value, is totally arbitrary, I just assumed that there was never gonna be a gauge with a -678 value. You can change it to any value not used by your gauges ;)
-        querries.push("insert into `gauges_statistics` select "+time_stamp+", '"+gaugeName+"', "+gaugeValue+" from dual where (select if(max(value),max(value),-678) from `gauges_statistics` where name = '"+gaugeName+"') = -678 OR (select value from `gauges_statistics` where name = '"+gaugeName+"' order by timestamp desc limit 0,1) <> "+gaugeValue+";")
+      querries.push("insert into `gauges_statistics` select "+time_stamp+", '"+gaugeName+"', "+gaugeValue+" from dual where (select if(max(value),max(value),-678) from `gauges_statistics` where name = '"+gaugeName+"') = -678 OR (select value from `gauges_statistics` where name = '"+gaugeName+"' order by timestamp desc limit 0,1) <> "+gaugeValue+";")^M

-      }
     }

     return querries;
```

Would a patch similar to the above diff be welcome and merged upstream? I can submit a PR in that case.

**Comment by fradinni** [comment]
@dpacaud, any idea about why we did it like that ( not storing 0 values ) ? I don't see any good reason to not store 0 values unless I missed something or maybe i just don't recall everything about it...

**Comment by dpacaud** [comment]
Hum, good question, it's been a while :)
I don't really remember but maybe we did not want to bloat the DB with zero values ?
Anyways, if this is needed for @pespin , I'd say let's merge it :)

**Comment by fradinni** [comment]
Alright, thank you @dpacaud ;)

**Comment by fradinni** [comment]
@pespin you can open a PR with your changes if you want, i'll check and merge it as soon as possible.
